# Npm server
FROM darh/php-essentials

WORKDIR /tmp
#RUN php -r "readfile('https://getcomposer.org/installer');" | php
RUN php -r "readfile('https://getcomposer.org/download/1.0.0-alpha8/composer.phar');" > /composer.phar
#RUN curl -sS https://getcomposer.org/download/1.0.0-alpha8/composer.phar > composer.phar


# RUN curl -sS https://getcomposer.org/installer | php -- --filename=composer.phar


# curl -sS https://getcomposer.org/installer | php
